import Head from "next/head";
import Image from "next/image";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AboutUs from "../src/components/AboutUs";
import Header, { Navigation } from "../src/components/Navigation";
import Services from "../src/components/Services";
import Reviews from "../src/components/Reviews";
// import GalleryComponent from '../src/components/GalleryComponent';
import { ApplyForm } from "../src/components/ApplyForm";
import ContactUs from "../src/components/ContactUs";
import Footer from "../src/components/Footer";
import { ScrollToTop } from "../src/components/buttons/ScrollToTop";
import { HeroBanner } from "../src/components/HeroBanner";

export default function Home() {
  return (
    <>
      <Head>
        <title>Katys Plumbing JETTT!!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <ScrollToTop />
        <Navigation/>
        <HeroBanner/>
        <AboutUs />
        <Services />
        <Reviews />
        {/* <GalleryComponent /> */}
        <ApplyForm />
        <ContactUs />
        <Footer />
        <ToastContainer />
      </>
    </>
  );
}
