import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import AboutUs from '../src/components/AboutUs';
import Header from '../src/components/Header';
import Services from '../src/components/Services';
import Reviews from '../src/components/Reviews';
// import GalleryComponent from '../src/components/GalleryComponent';
import { ApplyForm } from '../src/components/ApplyForm';
import ContactUs from '../src/components/ContactUs';
import Footer from '../src/components/Footer';
import { ScrollToTop } from '../src/components/buttons/ScrollToTop';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <>
        <ScrollToTop />
        <Header />
        <AboutUs />
        <Services />
        <Reviews />
        {/* <GalleryComponent /> */}
        <ApplyForm />
        <ContactUs />
        <Footer />
        <ToastContainer />
      </>
    </div>
  );
}
